version: "3"
services: 
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000 
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.maim:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=asdfdfgdgiodfagfghytuyteqewafdvghndsfgjnsdfloujfoerpujtmnclkdvj
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES= 30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES-DB=fastapi
      
    volumes:
       - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: